export const LESSONS = [
  {
    id: 1,
    title: "Chào hỏi đầu tiên",
    subtitle: "Chào hỏi, giới thiệu và tạm biệt",
    emoji: "👋",
    color: "coral",
  },
  {
    id: 2,
    title: "Người thân quanh mình",
    subtitle: "Gia đình, bạn bè và trường lớp",
    emoji: "🏡",
    color: "mint",
  },
  {
    id: 3,
    title: "Con số & giờ giấc",
    subtitle: "Đếm từ 1 đến 10 và hỏi giờ",
    emoji: "⏰",
    color: "gold",
  },
  {
    id: 4,
    title: "Việc mình làm mỗi ngày",
    subtitle: "Các động từ nền tảng thường gặp",
    emoji: "📖",
    color: "blue",
  },
  {
    id: 5,
    title: "Ăn uống & mua sắm",
    subtitle: "Gọi món, đồ uống và giá tiền",
    emoji: "🥟",
    color: "peach",
  },
  {
    id: 6,
    title: "Đi đâu, lúc nào?",
    subtitle: "Địa điểm, thời gian và thời tiết",
    emoji: "🌤️",
    color: "lavender",
  },
];

// Bộ khởi động HSK 1 gồm 72 từ/cụm từ nền tảng. Đây không phải danh mục
// từ vựng chính thức đầy đủ của một phiên bản kỳ thi HSK cụ thể.
export const VOCABULARY = [
  {
    id: "l1-nihao",
    lesson: 1,
    hanzi: "你好",
    pinyin: "nǐ hǎo",
    meaning: "xin chào",
    example: "你好！",
    examplePinyin: "Nǐ hǎo!",
    exampleMeaning: "Xin chào!",
  },
  {
    id: "l1-nin",
    lesson: 1,
    hanzi: "您",
    pinyin: "nín",
    meaning: "ngài; ông/bà/anh/chị (lịch sự)",
    example: "您好，老师！",
    examplePinyin: "Nín hǎo, lǎoshī!",
    exampleMeaning: "Em chào thầy/cô ạ!",
  },
  {
    id: "l1-wo",
    lesson: 1,
    hanzi: "我",
    pinyin: "wǒ",
    meaning: "tôi; mình",
    example: "我是学生。",
    examplePinyin: "Wǒ shì xuésheng.",
    exampleMeaning: "Tôi là học sinh.",
  },
  {
    id: "l1-ni",
    lesson: 1,
    hanzi: "你",
    pinyin: "nǐ",
    meaning: "bạn; cậu",
    example: "你好吗？",
    examplePinyin: "Nǐ hǎo ma?",
    exampleMeaning: "Bạn khỏe không?",
  },
  {
    id: "l1-ta-nam",
    lesson: 1,
    hanzi: "他",
    pinyin: "tā",
    meaning: "anh ấy; ông ấy",
    example: "他是我的朋友。",
    examplePinyin: "Tā shì wǒ de péngyou.",
    exampleMeaning: "Anh ấy là bạn của tôi.",
  },
  {
    id: "l1-ta-nu",
    lesson: 1,
    hanzi: "她",
    pinyin: "tā",
    meaning: "cô ấy; bà ấy",
    example: "她叫李月。",
    examplePinyin: "Tā jiào Lǐ Yuè.",
    exampleMeaning: "Cô ấy tên là Lý Nguyệt.",
  },
  {
    id: "l1-jiao",
    lesson: 1,
    hanzi: "叫",
    pinyin: "jiào",
    meaning: "gọi; tên là",
    example: "我叫安。",
    examplePinyin: "Wǒ jiào Ān.",
    exampleMeaning: "Tôi tên là An.",
  },
  {
    id: "l1-mingzi",
    lesson: 1,
    hanzi: "名字",
    pinyin: "míngzi",
    meaning: "tên; họ tên",
    example: "你的名字是什么？",
    examplePinyin: "Nǐ de míngzi shì shénme?",
    exampleMeaning: "Tên của bạn là gì?",
  },
  {
    id: "l1-hao",
    lesson: 1,
    hanzi: "好",
    pinyin: "hǎo",
    meaning: "tốt; khỏe; được",
    example: "今天天气很好。",
    examplePinyin: "Jīntiān tiānqì hěn hǎo.",
    exampleMeaning: "Hôm nay thời tiết rất đẹp.",
  },
  {
    id: "l1-ma",
    lesson: 1,
    hanzi: "吗",
    pinyin: "ma",
    meaning: "trợ từ nghi vấn …không?",
    example: "你是学生吗？",
    examplePinyin: "Nǐ shì xuésheng ma?",
    exampleMeaning: "Bạn có phải là học sinh không?",
  },
  {
    id: "l1-xiexie",
    lesson: 1,
    hanzi: "谢谢",
    pinyin: "xièxie",
    meaning: "cảm ơn",
    example: "谢谢你！",
    examplePinyin: "Xièxie nǐ!",
    exampleMeaning: "Cảm ơn bạn!",
  },
  {
    id: "l1-zaijian",
    lesson: 1,
    hanzi: "再见",
    pinyin: "zàijiàn",
    meaning: "tạm biệt; hẹn gặp lại",
    example: "老师，再见！",
    examplePinyin: "Lǎoshī, zàijiàn!",
    exampleMeaning: "Tạm biệt thầy/cô!",
  },

  {
    id: "l2-women",
    lesson: 2,
    hanzi: "我们",
    pinyin: "wǒmen",
    meaning: "chúng tôi; chúng ta",
    example: "我们学习汉语。",
    examplePinyin: "Wǒmen xuéxí Hànyǔ.",
    exampleMeaning: "Chúng tôi học tiếng Trung.",
  },
  {
    id: "l2-tamen",
    lesson: 2,
    hanzi: "他们",
    pinyin: "tāmen",
    meaning: "họ (nam hoặc nhóm chung)",
    example: "他们都是学生。",
    examplePinyin: "Tāmen dōu shì xuésheng.",
    exampleMeaning: "Họ đều là học sinh.",
  },
  {
    id: "l2-ren",
    lesson: 2,
    hanzi: "人",
    pinyin: "rén",
    meaning: "người",
    example: "那个人是谁？",
    examplePinyin: "Nà ge rén shì shéi?",
    exampleMeaning: "Người kia là ai?",
  },
  {
    id: "l2-pengyou",
    lesson: 2,
    hanzi: "朋友",
    pinyin: "péngyou",
    meaning: "bạn; bạn bè",
    example: "她是我的朋友。",
    examplePinyin: "Tā shì wǒ de péngyou.",
    exampleMeaning: "Cô ấy là bạn của tôi.",
  },
  {
    id: "l2-tongxue",
    lesson: 2,
    hanzi: "同学",
    pinyin: "tóngxué",
    meaning: "bạn học",
    example: "小王是我的同学。",
    examplePinyin: "Xiǎo Wáng shì wǒ de tóngxué.",
    exampleMeaning: "Tiểu Vương là bạn học của tôi.",
  },
  {
    id: "l2-laoshi",
    lesson: 2,
    hanzi: "老师",
    pinyin: "lǎoshī",
    meaning: "giáo viên; thầy/cô",
    example: "她是汉语老师。",
    examplePinyin: "Tā shì Hànyǔ lǎoshī.",
    exampleMeaning: "Cô ấy là giáo viên tiếng Trung.",
  },
  {
    id: "l2-xuesheng",
    lesson: 2,
    hanzi: "学生",
    pinyin: "xuésheng",
    meaning: "học sinh; sinh viên",
    example: "我是大学生。",
    examplePinyin: "Wǒ shì dàxuéshēng.",
    exampleMeaning: "Tôi là sinh viên đại học.",
  },
  {
    id: "l2-baba",
    lesson: 2,
    hanzi: "爸爸",
    pinyin: "bàba",
    meaning: "bố; ba",
    example: "我爸爸在家。",
    examplePinyin: "Wǒ bàba zài jiā.",
    exampleMeaning: "Ba tôi ở nhà.",
  },
  {
    id: "l2-mama",
    lesson: 2,
    hanzi: "妈妈",
    pinyin: "māma",
    meaning: "mẹ; má",
    example: "妈妈喜欢喝茶。",
    examplePinyin: "Māma xǐhuan hē chá.",
    exampleMeaning: "Mẹ thích uống trà.",
  },
  {
    id: "l2-jia",
    lesson: 2,
    hanzi: "家",
    pinyin: "jiā",
    meaning: "nhà; gia đình",
    example: "我家有四个人。",
    examplePinyin: "Wǒ jiā yǒu sì ge rén.",
    exampleMeaning: "Nhà tôi có bốn người.",
  },
  {
    id: "l2-shei",
    lesson: 2,
    hanzi: "谁",
    pinyin: "shéi",
    meaning: "ai",
    example: "他是谁？",
    examplePinyin: "Tā shì shéi?",
    exampleMeaning: "Anh ấy là ai?",
  },
  {
    id: "l2-de",
    lesson: 2,
    hanzi: "的",
    pinyin: "de",
    meaning: "trợ từ sở hữu; của",
    example: "这是我的书。",
    examplePinyin: "Zhè shì wǒ de shū.",
    exampleMeaning: "Đây là sách của tôi.",
  },

  {
    id: "l3-yi",
    lesson: 3,
    hanzi: "一",
    pinyin: "yī",
    meaning: "một; số 1",
    example: "我有一个朋友。",
    examplePinyin: "Wǒ yǒu yí ge péngyou.",
    exampleMeaning: "Tôi có một người bạn.",
  },
  {
    id: "l3-er",
    lesson: 3,
    hanzi: "二",
    pinyin: "èr",
    meaning: "hai; số 2",
    example: "今天是二号。",
    examplePinyin: "Jīntiān shì èr hào.",
    exampleMeaning: "Hôm nay là ngày mùng hai.",
  },
  {
    id: "l3-san",
    lesson: 3,
    hanzi: "三",
    pinyin: "sān",
    meaning: "ba; số 3",
    example: "桌子上有三本书。",
    examplePinyin: "Zhuōzi shàng yǒu sān běn shū.",
    exampleMeaning: "Trên bàn có ba quyển sách.",
  },
  {
    id: "l3-si",
    lesson: 3,
    hanzi: "四",
    pinyin: "sì",
    meaning: "bốn; số 4",
    example: "我家有四个人。",
    examplePinyin: "Wǒ jiā yǒu sì ge rén.",
    exampleMeaning: "Nhà tôi có bốn người.",
  },
  {
    id: "l3-wu",
    lesson: 3,
    hanzi: "五",
    pinyin: "wǔ",
    meaning: "năm; số 5",
    example: "现在五点。",
    examplePinyin: "Xiànzài wǔ diǎn.",
    exampleMeaning: "Bây giờ là năm giờ.",
  },
  {
    id: "l3-liu",
    lesson: 3,
    hanzi: "六",
    pinyin: "liù",
    meaning: "sáu; số 6",
    example: "我六点回家。",
    examplePinyin: "Wǒ liù diǎn huí jiā.",
    exampleMeaning: "Tôi về nhà lúc sáu giờ.",
  },
  {
    id: "l3-qi",
    lesson: 3,
    hanzi: "七",
    pinyin: "qī",
    meaning: "bảy; số 7",
    example: "一个星期有七天。",
    examplePinyin: "Yí ge xīngqī yǒu qī tiān.",
    exampleMeaning: "Một tuần có bảy ngày.",
  },
  {
    id: "l3-ba",
    lesson: 3,
    hanzi: "八",
    pinyin: "bā",
    meaning: "tám; số 8",
    example: "我们八点上课。",
    examplePinyin: "Wǒmen bā diǎn shàngkè.",
    exampleMeaning: "Chúng tôi vào học lúc tám giờ.",
  },
  {
    id: "l3-jiu",
    lesson: 3,
    hanzi: "九",
    pinyin: "jiǔ",
    meaning: "chín; số 9",
    example: "商店九点开门。",
    examplePinyin: "Shāngdiàn jiǔ diǎn kāimén.",
    exampleMeaning: "Cửa hàng mở cửa lúc chín giờ.",
  },
  {
    id: "l3-shi",
    lesson: 3,
    hanzi: "十",
    pinyin: "shí",
    meaning: "mười; số 10",
    example: "我有十本书。",
    examplePinyin: "Wǒ yǒu shí běn shū.",
    exampleMeaning: "Tôi có mười quyển sách.",
  },
  {
    id: "l3-ji",
    lesson: 3,
    hanzi: "几",
    pinyin: "jǐ",
    meaning: "mấy; bao nhiêu (số lượng nhỏ)",
    example: "你家有几个人？",
    examplePinyin: "Nǐ jiā yǒu jǐ ge rén?",
    exampleMeaning: "Nhà bạn có mấy người?",
  },
  {
    id: "l3-dian",
    lesson: 3,
    hanzi: "点",
    pinyin: "diǎn",
    meaning: "giờ; giờ đúng",
    example: "现在几点？",
    examplePinyin: "Xiànzài jǐ diǎn?",
    exampleMeaning: "Bây giờ là mấy giờ?",
  },

  {
    id: "l4-shi",
    lesson: 4,
    hanzi: "是",
    pinyin: "shì",
    meaning: "là; phải",
    example: "我是越南人。",
    examplePinyin: "Wǒ shì Yuènán rén.",
    exampleMeaning: "Tôi là người Việt Nam.",
  },
  {
    id: "l4-you",
    lesson: 4,
    hanzi: "有",
    pinyin: "yǒu",
    meaning: "có",
    example: "我有一本汉语书。",
    examplePinyin: "Wǒ yǒu yì běn Hànyǔ shū.",
    exampleMeaning: "Tôi có một quyển sách tiếng Trung.",
  },
  {
    id: "l4-zai",
    lesson: 4,
    hanzi: "在",
    pinyin: "zài",
    meaning: "ở; đang",
    example: "老师在学校。",
    examplePinyin: "Lǎoshī zài xuéxiào.",
    exampleMeaning: "Giáo viên ở trường.",
  },
  {
    id: "l4-qu",
    lesson: 4,
    hanzi: "去",
    pinyin: "qù",
    meaning: "đi; đến",
    example: "我明天去北京。",
    examplePinyin: "Wǒ míngtiān qù Běijīng.",
    exampleMeaning: "Ngày mai tôi đi Bắc Kinh.",
  },
  {
    id: "l4-lai",
    lesson: 4,
    hanzi: "来",
    pinyin: "lái",
    meaning: "đến; tới",
    example: "你什么时候来？",
    examplePinyin: "Nǐ shénme shíhou lái?",
    exampleMeaning: "Khi nào bạn đến?",
  },
  {
    id: "l4-kan",
    lesson: 4,
    hanzi: "看",
    pinyin: "kàn",
    meaning: "nhìn; xem; đọc",
    example: "爸爸在看书。",
    examplePinyin: "Bàba zài kàn shū.",
    exampleMeaning: "Ba đang đọc sách.",
  },
  {
    id: "l4-ting",
    lesson: 4,
    hanzi: "听",
    pinyin: "tīng",
    meaning: "nghe",
    example: "我喜欢听音乐。",
    examplePinyin: "Wǒ xǐhuan tīng yīnyuè.",
    exampleMeaning: "Tôi thích nghe nhạc.",
  },
  {
    id: "l4-shuo",
    lesson: 4,
    hanzi: "说",
    pinyin: "shuō",
    meaning: "nói",
    example: "她会说汉语。",
    examplePinyin: "Tā huì shuō Hànyǔ.",
    exampleMeaning: "Cô ấy biết nói tiếng Trung.",
  },
  {
    id: "l4-du",
    lesson: 4,
    hanzi: "读",
    pinyin: "dú",
    meaning: "đọc; học",
    example: "请读这个句子。",
    examplePinyin: "Qǐng dú zhè ge jùzi.",
    exampleMeaning: "Hãy đọc câu này.",
  },
  {
    id: "l4-xie",
    lesson: 4,
    hanzi: "写",
    pinyin: "xiě",
    meaning: "viết",
    example: "我写汉字。",
    examplePinyin: "Wǒ xiě Hànzì.",
    exampleMeaning: "Tôi viết chữ Hán.",
  },
  {
    id: "l4-xuexi",
    lesson: 4,
    hanzi: "学习",
    pinyin: "xuéxí",
    meaning: "học; học tập",
    example: "我们一起学习。",
    examplePinyin: "Wǒmen yìqǐ xuéxí.",
    exampleMeaning: "Chúng ta cùng học nhé.",
  },
  {
    id: "l4-gongzuo",
    lesson: 4,
    hanzi: "工作",
    pinyin: "gōngzuò",
    meaning: "làm việc; công việc",
    example: "妈妈在医院工作。",
    examplePinyin: "Māma zài yīyuàn gōngzuò.",
    exampleMeaning: "Mẹ làm việc ở bệnh viện.",
  },

  {
    id: "l5-chi",
    lesson: 5,
    hanzi: "吃",
    pinyin: "chī",
    meaning: "ăn",
    example: "我想吃米饭。",
    examplePinyin: "Wǒ xiǎng chī mǐfàn.",
    exampleMeaning: "Tôi muốn ăn cơm.",
  },
  {
    id: "l5-he",
    lesson: 5,
    hanzi: "喝",
    pinyin: "hē",
    meaning: "uống",
    example: "你喝茶吗？",
    examplePinyin: "Nǐ hē chá ma?",
    exampleMeaning: "Bạn có uống trà không?",
  },
  {
    id: "l5-shui",
    lesson: 5,
    hanzi: "水",
    pinyin: "shuǐ",
    meaning: "nước",
    example: "请给我一杯水。",
    examplePinyin: "Qǐng gěi wǒ yì bēi shuǐ.",
    exampleMeaning: "Cho tôi một cốc nước nhé.",
  },
  {
    id: "l5-cha",
    lesson: 5,
    hanzi: "茶",
    pinyin: "chá",
    meaning: "trà; chè",
    example: "爸爸喜欢喝茶。",
    examplePinyin: "Bàba xǐhuan hē chá.",
    exampleMeaning: "Ba thích uống trà.",
  },
  {
    id: "l5-mifan",
    lesson: 5,
    hanzi: "米饭",
    pinyin: "mǐfàn",
    meaning: "cơm (đã nấu)",
    example: "今天的米饭很好吃。",
    examplePinyin: "Jīntiān de mǐfàn hěn hǎochī.",
    exampleMeaning: "Cơm hôm nay rất ngon.",
  },
  {
    id: "l5-pingguo",
    lesson: 5,
    hanzi: "苹果",
    pinyin: "píngguǒ",
    meaning: "quả táo",
    example: "我买了三个苹果。",
    examplePinyin: "Wǒ mǎi le sān ge píngguǒ.",
    exampleMeaning: "Tôi đã mua ba quả táo.",
  },
  {
    id: "l5-mai",
    lesson: 5,
    hanzi: "买",
    pinyin: "mǎi",
    meaning: "mua",
    example: "我去商店买水。",
    examplePinyin: "Wǒ qù shāngdiàn mǎi shuǐ.",
    exampleMeaning: "Tôi đi cửa hàng mua nước.",
  },
  {
    id: "l5-qian",
    lesson: 5,
    hanzi: "钱",
    pinyin: "qián",
    meaning: "tiền",
    example: "这个多少钱？",
    examplePinyin: "Zhè ge duōshao qián?",
    exampleMeaning: "Cái này bao nhiêu tiền?",
  },
  {
    id: "l5-shangdian",
    lesson: 5,
    hanzi: "商店",
    pinyin: "shāngdiàn",
    meaning: "cửa hàng",
    example: "商店在学校前面。",
    examplePinyin: "Shāngdiàn zài xuéxiào qiánmiàn.",
    exampleMeaning: "Cửa hàng ở phía trước trường học.",
  },
  {
    id: "l5-duoshao",
    lesson: 5,
    hanzi: "多少",
    pinyin: "duōshao",
    meaning: "bao nhiêu",
    example: "一杯茶多少钱？",
    examplePinyin: "Yì bēi chá duōshao qián?",
    exampleMeaning: "Một cốc trà bao nhiêu tiền?",
  },
  {
    id: "l5-ge",
    lesson: 5,
    hanzi: "个",
    pinyin: "gè",
    meaning: "cái; người (lượng từ phổ biến)",
    example: "我想买一个苹果。",
    examplePinyin: "Wǒ xiǎng mǎi yí ge píngguǒ.",
    exampleMeaning: "Tôi muốn mua một quả táo.",
  },
  {
    id: "l5-xihuan",
    lesson: 5,
    hanzi: "喜欢",
    pinyin: "xǐhuan",
    meaning: "thích",
    example: "我喜欢中国菜。",
    examplePinyin: "Wǒ xǐhuan Zhōngguó cài.",
    exampleMeaning: "Tôi thích món ăn Trung Quốc.",
  },

  {
    id: "l6-zhongguo",
    lesson: 6,
    hanzi: "中国",
    pinyin: "Zhōngguó",
    meaning: "Trung Quốc",
    example: "北京在中国。",
    examplePinyin: "Běijīng zài Zhōngguó.",
    exampleMeaning: "Bắc Kinh ở Trung Quốc.",
  },
  {
    id: "l6-xuexiao",
    lesson: 6,
    hanzi: "学校",
    pinyin: "xuéxiào",
    meaning: "trường học",
    example: "我去学校。",
    examplePinyin: "Wǒ qù xuéxiào.",
    exampleMeaning: "Tôi đi đến trường.",
  },
  {
    id: "l6-yiyuan",
    lesson: 6,
    hanzi: "医院",
    pinyin: "yīyuàn",
    meaning: "bệnh viện",
    example: "妈妈在医院工作。",
    examplePinyin: "Māma zài yīyuàn gōngzuò.",
    exampleMeaning: "Mẹ làm việc ở bệnh viện.",
  },
  {
    id: "l6-fandian",
    lesson: 6,
    hanzi: "饭店",
    pinyin: "fàndiàn",
    meaning: "nhà hàng; khách sạn",
    example: "我们去饭店吃饭。",
    examplePinyin: "Wǒmen qù fàndiàn chīfàn.",
    exampleMeaning: "Chúng tôi đi nhà hàng ăn cơm.",
  },
  {
    id: "l6-jintian",
    lesson: 6,
    hanzi: "今天",
    pinyin: "jīntiān",
    meaning: "hôm nay",
    example: "今天星期五。",
    examplePinyin: "Jīntiān xīngqīwǔ.",
    exampleMeaning: "Hôm nay là thứ Sáu.",
  },
  {
    id: "l6-mingtian",
    lesson: 6,
    hanzi: "明天",
    pinyin: "míngtiān",
    meaning: "ngày mai",
    example: "明天见！",
    examplePinyin: "Míngtiān jiàn!",
    exampleMeaning: "Hẹn gặp ngày mai!",
  },
  {
    id: "l6-zuotian",
    lesson: 6,
    hanzi: "昨天",
    pinyin: "zuótiān",
    meaning: "hôm qua",
    example: "昨天我在家。",
    examplePinyin: "Zuótiān wǒ zài jiā.",
    exampleMeaning: "Hôm qua tôi ở nhà.",
  },
  {
    id: "l6-xianzai",
    lesson: 6,
    hanzi: "现在",
    pinyin: "xiànzài",
    meaning: "bây giờ; hiện tại",
    example: "现在几点？",
    examplePinyin: "Xiànzài jǐ diǎn?",
    exampleMeaning: "Bây giờ là mấy giờ?",
  },
  {
    id: "l6-tianqi",
    lesson: 6,
    hanzi: "天气",
    pinyin: "tiānqì",
    meaning: "thời tiết",
    example: "今天天气怎么样？",
    examplePinyin: "Jīntiān tiānqì zěnmeyàng?",
    exampleMeaning: "Thời tiết hôm nay thế nào?",
  },
  {
    id: "l6-re",
    lesson: 6,
    hanzi: "热",
    pinyin: "rè",
    meaning: "nóng",
    example: "今天很热。",
    examplePinyin: "Jīntiān hěn rè.",
    exampleMeaning: "Hôm nay rất nóng.",
  },
  {
    id: "l6-leng",
    lesson: 6,
    hanzi: "冷",
    pinyin: "lěng",
    meaning: "lạnh",
    example: "北京的冬天很冷。",
    examplePinyin: "Běijīng de dōngtiān hěn lěng.",
    exampleMeaning: "Mùa đông ở Bắc Kinh rất lạnh.",
  },
  {
    id: "l6-xiayu",
    lesson: 6,
    hanzi: "下雨",
    pinyin: "xiàyǔ",
    meaning: "mưa; trời mưa",
    example: "今天下雨了。",
    examplePinyin: "Jīntiān xiàyǔ le.",
    exampleMeaning: "Hôm nay trời mưa rồi.",
  },
];

export const WRITING_WORDS = VOCABULARY.filter(
  (word) => Array.from(word.hanzi).length === 1,
);

export function getLessonWords(lessonId) {
  return VOCABULARY.filter((word) => word.lesson === Number(lessonId));
}

export function getWord(wordId) {
  return VOCABULARY.find((word) => word.id === wordId);
}
